image:
  repository: nginxinc/nginx-unprivileged
  tag: 1.27-alpine
  pullPolicy: IfNotPresent

host: daviddempsey.dev

replicaCount: 1

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

imagePullSecrets: []
