image:
  repository: nginxinc/nginx-unprivileged
  tag: 1.27-alpine
  pullPolicy: IfNotPresent

host: daviddempsey.dev

auth:
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.15.2
  issuer: https://auth.daviddempsey.dev
  existingSecret: daviddempsey-dev-auth

replicaCount: 1

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

imagePullSecrets: []
