apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "daviddempsey-dev.fullname" . }}-site
  labels:
    {{- include "daviddempsey-dev.labels" . | nindent 4 }}
data:
  index.html: |
{{ .Files.Get "files/index.html" | indent 4 }}
  styles.css: |
{{ .Files.Get "files/styles.css" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "daviddempsey-dev.fullname" . }}-nginx
  labels:
    {{- include "daviddempsey-dev.labels" . | nindent 4 }}
data:
  default.conf: |
{{ .Files.Get "files/nginx.conf" | indent 4 }}
