apiVersion: v1
kind: Service
metadata:
  name: {{ include "daviddempsey-dev.fullname" . }}
  labels:
    {{- include "daviddempsey-dev.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "daviddempsey-dev.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 4180
      targetPort: http
